### ISSUE TITLE
Schema validation with the key "exclusiveMinimum" fails using "PropertyTreeAdapter"

### ISSUE THREAD

**Issue by davtorresg** [tristanpenman/valijson#11]
I have tested the following json: {"id":2, "name":"Door","price":0}. The json schema for the validation of "id" and "name" is working correctly but not for the property "price". This property has the following definition:
  "price": {"type": "number", "minimum" : 0,  "exclusiveMinimum" : true}

If I execute this code with the example "external_schema" is working fine. I get an appropriate error message: "Expected number greater than 0"

**Comment by tristanpenman** [comment]
You're finding some important issues here. I have just had a look at what is happening with this one, and it comes down to how types are being checked before applying further constraint logic. As an example, the validation code for `MinimumConstraint` (used by 'minimum' and 'exclusiveMinimum' constraints) first checks whether a value is a number, and only performs a range check if it is. Non-numeric values are simply treated as valid.

Since Boost Property Trees are limited to storing strings, this check happens in quite a few places in the `ValidationVisitor` class. I'm going to go through the code and clean up any that I find.

**Comment by tristanpenman** [comment]
I've pushed some changes as part of a64c3c4 that should address this issue. I am also going to integrate these changes into the 'refactor-memory-management' branch, so keep an eye on that if you're interested in what the constraint structs will look like with better encapsulation.

**Comment by davtorresg** [comment]
Thank you very much for the explanation. I hadn't realized that there was another branch called "refactor-memory-management" but I will have a look to this branch also :)
