### ISSUE TITLE
question: boost::json support?

### ISSUE THREAD

**Issue by roddypratt** [tristanpenman/valijson#117]
Boost 1.75 introduces a new boost::json library- I'm considering switching to it, but does it need a new adapter for valijson?

https://www.boost.org/doc/libs/1_75_0/libs/json/doc/html/index.html

**Comment by tristanpenman** [comment]
It looks like a new adapter will be required. Unfortunately, the existing boost::property_tree adapter is very limited in its support for JSON types, so this will be an entirely new API.

**Comment by matty0ung** [comment]
I have had a stab at this in https://github.com/tristanpenman/valijson/pull/136 because I really wanted to use both Valijson and Boost.JSON.  All the tests pass on my machine.

Although the Boost.JSON API is very different from Property Tree, it's similar to a number of the other JSON libraries, so it wasn't a huge undertaking to get something working.  (You have the option to use custom memory allocators in Boost.JSON, but it's not required, so I haven't tried to do anything clever there with the new adapter for Valijson.)

**Comment by tristanpenman** [comment]
This has been merged in 2ecd2119522e9acfabffc9442718d61aa31de92b and will be included in a v0.6 release shortly.
