### ISSUE TITLE
Compilation warning treats as errors

### ISSUE THREAD

**Issue by davtorresg** [tristanpenman/valijson#12]
In my project, I compiled with the options "-Wall -Werror" in order to treat all the warnings as errors. I am facing several warnings of the type "comparison between signed and unsigned integer expressions". 

Analysing this scenario I have one question. For example, in the class "concrete_constraints.hpp" we find the struct "MaxLengthConstraint" that is defined like "int64_t". Later, this value will be compared with a "size_t" (warnings) and the warning appears. 

Now my question, I don't understand why "concepts" like "maxItems", "minItems", "maxProperties" and "mimProperties" are "int64_t". Are there scenarios where this values could have a negative value?

If they were defined like "uint64_t" several warnings would disappear.

**Comment by tristanpenman** [comment]
I honestly do not remember if there was a justification for defining these constraints using 'int64_t` values, other than a general preference to use signed types when the distinction is not terribly important.  But I agree that it does not make sense to use `int64_t` in these cases, as they are only ever going to be compared with other unsigned values.

I'm currently working on a branch (refactor-memory-management) in which I have cleaned up and refactored those constraint structs along with some other changes related to memory management. The motivation for the branch was to improve encapsulation so that the library could eventually support custom allocators. That branch is close to being merged into master, so I'll apply your suggestions there.

**Comment by davtorresg** [comment]
Ok, just to let you know another warning that it could be easily cleaned. In the class "validation_visitor.hpp", in the constructor, you initialized the member "strictTypes" before than "results", however, in the section of the attributes of the class, "results" was written before than "strictTypes"

**Comment by tristanpenman** [comment]
These issues should all be resolved as of commit ee2d247. Feel free to open a new issue if there are any other issues relating to warnings.
