### ISSUE TITLE
Warnings - code unreachable 

### ISSUE THREAD

**Issue by NairaP** [tristanpenman/valijson#125]
**MSVC (in release build only)**
**valijson  v0.3**

Configuration: Release Win32 ------
2>Generating code
include\valijson\validation_visitor.hpp(622): error C2220: the following warning is treated as an error
include\valijson\validation_visitor.hpp(622): warning C4702: unreachable code

include\valijson\validation_visitor.hpp(623): warning C4702: unreachable code
include\valijson\validation_visitor.hpp(626): warning C4702: unreachable code
include\valijson\validation_visitor.hpp(627): warning C4702: unreachable code
include\valijson\validation_visitor.hpp(631): warning C4702: unreachable code
include\valijson\validation_visitor.hpp(499): warning C4702: unreachable code
include\valijson\validation_visitor.hpp(500): warning C4702: unreachable code

**Comment by tristanpenman** [comment]
Hi @NairaP, thanks for letting me know about this. Can you tell me which version of MSVC you are using?

**Comment by NairaP** [comment]
Hi @tristanpenman, 
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.25)

**Comment by tristanpenman** [comment]
Hi @NairaP, I finally had a chance to look at this issue. I've attempted to resolve the issues in commit cb778b6. Those unreachable code warnings appeared to be a false positive, related to how MSVC optimises exception handling. Wrapping the offending code in a redundant try/catch seemed to do the trick.

For this to work, I think you will need to ensure that `VALIJSON_USE_EXCEPTIONS=1` is included in your preprocessor definitions.

If you still see any warnings when you compile the code, feel free to re-open this issue.

**Comment by NairaP** [comment]
Hi @tristanpenman, thanks for the fix. It actually resolved most of the warnings, but some of them still exist.
![image](https://user-images.githubusercontent.com/24406150/125651409-e5303bdc-0e19-42b4-8d97-b6e86e8980e7.png)

`include\valijson\validation_visitor.hpp`
I tried applying the try/catch also to the  
-  `bool visit(const MaxItemsConstraint &constraint) override;` 
-  `bool visit(const MinItemsConstraint &constraint) override`
and that works ok now. Please fix that too. 

Thanks :)

**Comment by tristanpenman** [comment]
I've done some more investigation into this issue. It seemed strange that you were getting a different set of compiler warnings. It turns out that this depends heavily on the optimisation and inlining settings used for the build. And at certain levels, the issue is much more pervasive.

The problem is that the warning is generated based on the code that MSVC analyses, after applying pre-processors, so it's difficult to address all of the cases without making the code less readble. It is also a moving target, as the optimiser and inliner become more aggressive.

Instead, I've decided to disable those warnings, just for the relevant headers (using a pragma). This will allow the compiler to optimise as much as it wants, without spamming your build with warnings. The commit is 855365b
