### ISSUE TITLE
Issue if no test & no examples

### ISSUE THREAD

**Issue by MDesharnaisX** [tristanpenman/valijson#127]
Hi,
In the CMakeList.txt, there is this code :
`
if(NOT valijson_BUILD_TESTS AND NOT valijson_BUILD_EXAMPLES)
    return()
endif()
`
If you activate neither tests nor example, you loose all what is after. Among which you have no more exceptions, you loose Qt5 support ....
I advise to remove these lines

Hope it will help.

**Comment by tristanpenman** [comment]
The CMake files are primarily intended to support the test harness and example codes, although I suppose they could also be used to install the headers locally.

Just so that I'm clear on your use case, are you including Valijson in your project as a vendored library, or are you relying on it being available at a system level (e.g. in /usr/include) and using CMake to install them?

I don't see any problem with making the change - just want to understand how it is being used, so that any further development takes that into account :)

**Comment by MDesharnaisX** [comment]
I'm using valijson as a vendor library.

**Comment by tristanpenman** [comment]
I've had a bit of a closer look at this, and I think changing the CMakeLists.txt file will have unintended effects. As I mentioned above, the purpose of the CMakeLists.txt here is to build the tests and the examples. If those are disabled, then it is expected that nothing will be built.

Valijson is designed to be a header only library. If you are vendoring the library, then it should be a matter of setting the correct CMake directives in your CMakeLists.txt file so that valijson/include is in your include path. You will also need to ensure that your JSON parser library (sounds like you might be using Qt5) is also in your include path.

Hope this helps.
