### ISSUE TITLE
MSVC C++17: Compile Error C4996 use of std::iterator deprecated (v.0.4)

### ISSUE THREAD

**Issue by schoetbi** [tristanpenman/valijson#129]
After upgrading my project to C++17 I get the following error message:

Error	C4996	'std::iterator<std::bidirectional_iterator_tag,valijson::adapters::NlohmannJsonAdapter,ptrdiff_t,valijson::adapters::NlohmannJsonAdapter *,valijson::adapters::NlohmannJsonAdapter &>': 
warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) 
The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators. 
You can define _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by tristanpenman** [comment]
Thanks for taking the time to raise this issue. I've gone through the adapter headers and removed the use of `std::iterator` in all those. I also noticed that the bundled version of rapidjson (v1.1) was also using `std::iterator`. Unfortunately there has not been a release of rapidjson since 1.1, but I found that the issue had been addressed in their github repo. I've updated the bundled version to use the latest code.
