### ISSUE TITLE
Error validation in a property constraint define in "oneOf"

### ISSUE THREAD

**Issue by davtorresg** [tristanpenman/valijson#14]
In my schema I have defined the following property:
"id": {"type": "string",
          "oneOf": [ {"format": "ipv4"}, {"format": "ipv6"}  ]
       }

However, when I send a Json with the property "id": "192.165.12.10", the example "external_schema" returns the following error:

Validation failed.
Error #1
  context: <root>["id"]
  desc:    Failed to validate against exactly one child schema.
Error #2
  context: <root>
  desc:    Failed to validate against schema associated with property name 'id' in properties constraint.

**Comment by tristanpenman** [comment]
It looks like there are two issues here.

First is that Valijson doesn't actually support the 'format' constraint. JSON Schema v4 declares 'format' support as being optional, and I didn't need it personally, so it ended up quite low on my list of priorities. On its own, this means that the constraint is ignored, and will not cause a document to be considered invalid. The omission of 'format' support is documented in the README, but it is possibly not prominent enough...

The other issue is that a 'oneOf' constraint differs from an 'anyOf' constraint in that a document or value must validate against *exactly one* of the sub-schemas provided. This doesn't work well with 'format' here, since any value would be considered valid against both sub-schemas.

As far as I can tell, Valijson is doing the right thing according to the v4 spec. But if you have other ideas, we might be able to come up with a solution that is more user friendly.

**Comment by tristanpenman** [comment]
Closing this issue for now, as it does not seem like a resolution is needed at this stage.
