### ISSUE TITLE
Inspector is crashing if schema contains the unknown type

### ISSUE THREAD

**Issue by xgsa** [tristanpenman/valijson#141]
I have tried using the inspector GUI app and it crashes if to pass the following schema to it: `{"type":"S"}`.
It prints:
```
Unrecognised JSON type name 'S'
Aborted (core dumped)
```
into console (I am using it on Ubuntu 20.04). 
Looks like some exceptions are not handled properly.

**Comment by tristanpenman** [comment]
Thanks for reporting this. It looks like this was an oversight when the use of exceptions was made optional. It is now necessary to define `VALIJSON_USE_EXCEPTIONS` to enable exceptions. If this is not defined, the process will just call `abort`.

In retrospect it may have made more sense to define `VALIJSON_NO_EXCEPTIONS` and leave exceptions enabled by default, but I know that there are active projects that rely on the current behaviour, and want to avoid making any disruptive changes.

In any case, I've added the necessary `VALIJSON_USE_EXCEPTIONS` definition for the inspector example, so that should all be working as of commit 4990e352a710eb2eb6dc43e288e59441297c7b2f.
