### ISSUE TITLE
Inspector doesn't validate some documents correctly

### ISSUE THREAD

**Issue by xgsa** [tristanpenman/valijson#142]
I am trying to use the inspector to try the valijson library on practice and it fails to validate the following case:
Schema: `{"type":"string"}`
Data: `"q"`
Even more interesting that the result depends on the order in which schema or data is added into text boxes. If to add schema and then data the error is `illegal value`:
![Screenshot_20211105_131410](https://user-images.githubusercontent.com/875362/140502321-f37f561a-0694-4e27-98a9-64b70fbd2857.png)
If data then schema the error is `Error #1
  context: <root>
  desc:    Value type not permitted by 'type' constraint.
`
![Screenshot_20211105_131301](https://user-images.githubusercontent.com/875362/140502209-cb3e8f4c-b6cb-4d6c-be22-e58537b68794.png)
The expected result is that validation passes.
It is also important that the same data for external_schema.cpp example passes the validation.

**Comment by tristanpenman** [comment]
Hi @xgsa, thanks for the feedback. I had a look into this and found that there were two issues at play. First is that QtJson, which this example is based on, does not consider non-array and non-object values to be valid JSON documents. My understanding is that this is a somewhat informal part of the JSON spec, and that nowadays it is more common for parsers to support it.

The second issue was just that I was trying to be too clever with when each document was being parsed and validated. I've simplified things so that both document and schema errors are shown at the same time.

And for the first issue, I've included a note in the app to explain that. These changes were all merged in d34f78b.

Feel free to re-open this issue if I've failed to address any of your concerns.
