### ISSUE TITLE
Strange issue with boost::json

### ISSUE THREAD

**Issue by sptrakesh** [tristanpenman/valijson#151]
Hello,

I was experimenting with replacing my previous RapidJSON based schema validator with boost::json based validator.  When using the BoostJsonAdapter, I get an infinite loop, which I tracked down to the `find` function.  I wrote a simple test program to see if I can replicate it directly using boost::json, but that does not seem to have the issue.  I did not change any current code, just the names when I tried to switch over from RapidJSON, so not sure if I missed some requisite step when migrating to boost::json.

```c++
#include <boost/json/src.hpp>
#include <valijson/adapters/boost_json_adapter.hpp>
#include <valijson/schema.hpp>
#include <valijson/schema_parser.hpp>
#include <iostream>

using namespace std::string_literals;
namespace json = boost::json;

int main()
{
  auto data = R"({
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for a product",
      "type": "integer"
    },
    "name": {
      "description": "Name of the product",
      "type": "string"
    },
    "price": {
      "type": "number",
      "minimum": 0
    },
    "tags": {
      "type": "array",
      "items": { "type": "string" },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": ["id", "name", "price" ]
})"s;

  json::error_code ec;
  auto value = json::parse( data, ec );
  if ( ec ) 
  {
    std::cerr << "Error parsing json " << ec.message() << std::endl;
    return 1;
  }

  const auto obj = value.as_object();
  auto iter = obj.find("$schema");
  if ( iter == obj.cend() )
  {
    std::cerr << "Error finding key $schema" << std::endl;
    return 2;
  }

  iter = obj.find("$ref");
  if ( iter != obj.cend() )
  {
    std::cerr << "Invalid iterator for non-existent key $ref" << std::endl;
    return 3;
  }

  valijson::Schema s;
  valijson::SchemaParser sp{ valijson::SchemaParser::Version::kDraft4 };
  valijson::adapters::BoostJsonAdapter a( obj );
  std::cout << "Populating schema..." << std::endl;
  sp.populateSchema( a, s ); // infinite loop here trying to find $ref
}
```

**Comment by tristanpenman** [comment]
Hi @sptrakesh, it took a few days but I finally had a chance to look at this. It was pretty confusing at first, because like you discovered, the `find` function works fine when you apply it directly.

I suspected that the object reference that was being passed to the adapter was later becoming invalid. I was able to get it working by changing the final block of code to this:
```
  valijson::Schema s;
  valijson::SchemaParser sp{ valijson::SchemaParser::Version::kDraft4 };
  // changed from 'obj' to 'value' on the next line:
  valijson::adapters::BoostJsonAdapter a( value );
  std::cout << "Populating schema..." << std::endl;
  sp.populateSchema( a, s ); // infinite loop here trying to find $ref
```
I believe what was happening is that `obj` was being cast back to a `boost::json::value` type, which was then cleaned up when the constructor returned.

I've marked the relevant constructors as deleted for now, to avoid this happening accidentally. I've also included a slightly extended version of your example code. This is all in commit 7d4ea90.
