### ISSUE TITLE
Support for JsonCpp 1.9.5

### ISSUE THREAD

**Issue by bsbontchev** [tristanpenman/valijson#153]
Valijson with JsonCpp 1.9.5 in the presence of a "pattern" key, e.g. regular expressions, the jsoncpp adapter stops parsing at the first pattern occurrence.

**Comment by tristanpenman** [comment]
Hi @bsbontchev, thanks for reporting this issue. I tried updating the vendored version of jsoncpp to 1.9.5, and the test suite still runs successfully. Are you able to provide a code sample, or even the JSON schema document, that is failing for you?

**Comment by bsbontchev** [comment]
[valijson.zip](https://github.com/tristanpenman/valijson/files/8035357/valijson.zip)
The zip contains the test application. 
Unzip, change the paths to your jsoncpp, make.
Run: build/test test.schema.json test.json > test.txt
The output should be something like this:
arg_initialize() result: 1
GCC version: 4.8.5
JSONCPP version: 1.9.5
sdk_initialize()
validate() schema error: regex_error (4): The expression contains mismatched square brackets ('[' and ']')
test_initialize() result: 0
sdk_shutdown()
main() result: 0

**Comment by tristanpenman** [comment]
Thanks for packaging that up. Here are the results I got when I tested this on my regular dev machine (for reference, macOS Monterey 12.2 and clang 13):

```
 $ ./build/test test.schema.json test.json

arg_initialize() result: 1
GCC version: 4.2.1
JSONCPP version: 1.9.5
sdk_initialize()
test_initialize() result: 1
test_shutdown() result: 1
sdk_shutdown()
main() result: 1
```

I also tried creating an intentionally invalid test file:
```
 $ cat test-invalid.json
{
	"version": "invalid"
}
```

Running the test program on that produced this:
```
 $ ./build/test test.schema.json test-invalid.json

arg_initialize() result: 1
GCC version: 4.2.1
JSONCPP version: 1.9.5
sdk_initialize()
validate() schema results: {
	{
		"context": "/version",
		"error": "Failed to match regex specified by 'pattern' constraint."
	}
,	{
		"context": "/",
		"error": "Failed to validate against schema associated with property name 'version'."
	}
}
test_initialize() result: 0
sdk_shutdown()
main() result: 0
```

Is that the expected behaviour?

My best guess at this stage is that the regex is being parsed differently because of locale configuration. 

I also have a Linux dev machine, and can try on that as well if that may help.

**Comment by bsbontchev** [comment]
Our dev/build machines use default installation so the builds are compatible with our customers.
On CentOS 8.0 it works:
./build/test test.schema.json test.json 
arg_initialize() result: 1
GCC version: 8.4.1
JSONCPP version: 1.9.5
sdk_initialize()
test_initialize() result: 1
test_shutdown() result: 1
sdk_shutdown()
main() result: 1

The issue is on CentOS 7.0.
./build/test test.schema.json test.json 
arg_initialize() result: 1
GCC version: 4.8.5
JSONCPP version: 1.9.5
sdk_initialize()
validate() schema error: regex_error (4): The expression contains mismatched square brackets ('[' and ']')
test_initialize() result: 0
sdk_shutdown()
main() result: 0

I suspect that it is the GCC compiler or the libs, maybe a type conversion, regex parsing or escape character manipulation.

**Comment by tristanpenman** [comment]
I do recall that when I was first implementing pattern support, early GCC implementations of `<regex>` were problematic. Based on this Stack Overflow post, I suspect that will be the problem here:
https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

It appears that full support only arrived in GCC 4.9.0.

**Comment by tristanpenman** [comment]
Hey @bsbontchev, I'm going to close this issue for now since supporting older versions of GCC (i.e. < 5.x) does not really align with the goals of the project.

However, feel free to re-open the issue if you end up integrating pcre and think it could be a sustainable addition to the project. I'd be more than happy to collaborate on a PR.
