### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [tristanpenman/valijson#167]
I noticed that the current releases for this project are all marked as `pre release`, I wonder if that is intentional.

Context, I am trying to [include this project into homebrew-core](https://github.com/Homebrew/homebrew-core/pull/114312), and we have some guidelines of not including unstable releases. 

Thanks!

**Comment by tristanpenman** [comment]
Hey @chenrui333, thanks for you interest in this library. That's a good question about the pre-release label. I originally published the library using the pre-release label because I intended to make some breaking changes in the lead-up to 1.0. However, that was many years ago, and I feel that the library been stable for so long that a 1.0 release would be justified.

I'll do that shortly, and let you know when it is ready.

**Comment by tristanpenman** [comment]
Done: https://github.com/tristanpenman/valijson/releases/tag/v1.0

**Comment by chenrui333** [comment]
Thanks @tristanpenman! That makes my life easier. :)
