### ISSUE TITLE
CMakeLists.txt : Updating `cmake_minimum_required` to > 3.5

### ISSUE THREAD

**Issue by IzawGithub** [tristanpenman/valijson#184]
Hello, thank you for the useful library!

I am using this project in an application managed with CMake. CMake 3.27 has issued a deprecation notice if the minimum required version is less than 3.5 . This is a problem if warning are treated as error, as it can fail build that would otherwise be fine, and removing warning as error could lead to missing some potential future problem.

Changing the minimum required version naturally remove the deprecation notice. I have not tested in extensive detail a newer version, but `3.6.0` seems to compile successfully. However, I would guess than choosing a new minimum version is a bit more nuanced than eyeballing it, and I don't have the required CMake knowledge to be more of an help on this issue.

**Comment by tristanpenman** [comment]
I think this is a low risk change, since anyone depending on much older versions of CMake can always use a specific git ref to access the older version of CMakeLists.txt.

This has been updated in [9de00d7](https://github.com/tristanpenman/valijson/commit/9de00d75b40d1098a24b8eccfcdc603fece80c3a). Feel free to re-open this ticket if this doesn't resolve the issue for you.
