### ISSUE TITLE
using PropertyTreeAdapter gives different( and inferior) errors that jsoncpp

### ISSUE THREAD

**Issue by jhjensen** [tristanpenman/valijson#22]
in the attached program JsonCppAdapter gives this error:

```
Expected number greater than or equal to 0<root>[ttl]
```

where PropertyTreeAdapter gives:

```
Value type not permitted by 'type' constraint.<root>[ttl]
```

The first error is more descriptive of the problem.

It does this regardless if the schema is built with property trees, or jsoncpp.

[ptreeTest.zip](https://github.com/tristanpenman/valijson/files/169766/ptreeTest.zip)

**Comment by jhjensen** [comment]
does PropertyTree adapter support integer constraints?

**Comment by tristanpenman** [comment]
It has been long enough that this is probably no longer relevant to you, but your example code instantiates `valijson::Validator` using the default constructor, which enables strict type checking. And since Boost property trees store values as strings, an integer type constraint will be violated, even if the value _looks_ like an integer. 

This limitation in Boost property trees was actually the motivation for supporting both strong and weak types. It meant that, while values stored in property trees could not be type-constrained, they could be validated using various other constraints.
