### ISSUE TITLE
 <optional> only works with c++17 and can't find <compat/optional>

### ISSUE THREAD

**Issue by v-miswar** [tristanpenman/valijson#45]
in basic_adapter.hpp there is this part:

```
#if __has_include(<optional>)
#  include <optional>
namespace opt = std;
#else
#  include <compat/optional.hpp>
namespace opt = std::experimental;
#endif
```

on Visual Studio 2017 I get optional is only available with c++17, if I just try <compat/optional.hpp> it says this file is not found.

Any suggestions?

**Comment by tristanpenman** [comment]
The first thing I would check is that the include path for your project contains 'path_to_valijson/include' rather than 'path_to_valijson/include/valijson'. The 'compat' directory was intended to be more of a temporary fix, so it was placed alongside the main 'valijson' directory.

Then, assuming that your include path has been configured correctly, it may be that VS 2017 is behaving different with regard to using angle brackets instead of quotes for the `#include`. So my second suggestion would be to try using quotes.

**Comment by v-miswar** [comment]
This gave me the information I needed. I didn't notice that you included a compat->optional.hpp file so once I included that it all worked. THanks!
