### ISSUE TITLE
Valijson with nlohmann json

### ISSUE THREAD

**Issue by monstasat** [tristanpenman/valijson#47]
Hello! 

I am trying to use your library to validate json objects generated by nlohmann json library. In your readme there is a note that valijson is compatible with nlohmann json v1.1.0, and I am trying to use it with 2.1.1. During validation, I have the following exception thrown by valijson:
```
unhandled exception (type std::exception) in signal handler:
what: JSON value cannot be cast to an object.
```

Here is my validation code:
```
json j_schema =
        json{{"comment", "JSON schema for test"},
             {"type", "object"},
             {"required", {"prop3"}},
             {"properties", {{"prop1", {"type", "array"}},
                             {"prop2", {"type", "object"}},
                             {"prop3", {"type", "number"}}}}};

    using valijson::Schema;
    using valijson::SchemaParser;
    using valijson::Validator;
    using valijson::ValidationResults;
    using valijson::adapters::NlohmannJsonAdapter;

    Schema schema;
    SchemaParser parser;
    NlohmannJsonAdapter schema_doc(j_schema);
    parser.populateSchema(schema_doc, schema);

    Validator validator;
    NlohmannJsonAdapter doc(j);
    ValidationResults results;

    if (!validator.validate(schema, doc, &results)) {
        std::string err = "JSON validation failed.\n";
        ValidationResults::Error error;
        int err_num = 1;
        while (results.popError(error)) {
            std::string context;
            std::vector<std::string>::iterator it = error.context.begin();
            for (; it != error.context.end(); it++)
                context += *it;

            err += "Error #" + std::to_string(err_num) + "\n";
            err += " context: " + context + "\n";
            err += " description: " + error.description + "\n";

            ++err_num;
        }
        std::cout << err << "\n";
        return;
    }
```

It seems that this exception appears while converting json object to NlohmannJsonAdapter. This exception is thrown in basic_adapter.hpp, at line 439. I didn't understand the code of valijson yet, so I don't know what causes this exception to be thrown. Can somebody help with this issue?

Did somebody test valjson with new versions of nlohmann json? Is valijson working out of the box with new versions of nlohmann json or does it need some modifications?

**Comment by cmannett85** [comment]
Your schema is invalid, `required` **must** be an array (see 6.5.3 of the validation RFC draft).

**Comment by tristanpenman** [comment]
Thanks for the detailed code sample. That has allowed me to reproduce the issue, and improve the error message produced by Valijson when extracting a schema from your JSON document.

What is going wrong here relates to how nlohmann json is parsing your schema document. Specifically, the problem is caused by properties constraints. I've included your schema here for reference:
```
json j_schema =
        json{{"comment", "JSON schema for test"},
             {"type", "object"},
             {"required", {"prop3"}},
             {"properties", {{"prop1", {"type", "array"}},
                             {"prop2", {"type", "object"}},
                             {"prop3", {"type", "number"}}}}};
```

When nlohmann json processes `{"type", "array"}`, it is parsing that as an array, whereas properties constraints must be objects. If you instead write `{{"type", "array"}}`, it will be parsed as an object.

Valijson's error message was not at all helpful here, and so I have updated that in 5d9b42a, so that it includes a path to the error, and details about the type mismatch.
