### ISSUE TITLE
Rapidjson Adapter assumes MemoryPoolAllocator

### ISSUE THREAD

**Issue by MikaelSmith** [tristanpenman/valijson#7]
We've found the rapidjson MemoryPoolAllocator is buggy on SPARC, and for the moment we're avoiding it as not being a large performance benefit. The adapter assumes MemoryPoolAllocator, so we can't use valijson without it.

I'm working on a patch to templatize the adapter so it can take any rapidjson GenericValue type.

**Comment by tristanpenman** [comment]
I'm not surprised to hear that you're seeing issues there. If I remember correctly, the SPARC architecture is pretty unforgiving when it comes to memory alignment.

It turns out that RapidJSON has been updated since it was first included in the valijson repo. Will you be working with the version of RapidJSON that is currently included in the repo?

**Comment by MikaelSmith** [comment]
I'm expecting to work with a recent version of RapidJSON from https://github.com/miloyip/rapidjson.

**Comment by MikaelSmith** [comment]
The AdapterTraits class is problematic, but as it doesn't seem to be used anywhere it seems like I can ignore generalizing it.

**Comment by tristanpenman** [comment]
Closing this issue since the RapidJson adapter has been updated as per Mikael's patch.
