### ISSUE TITLE
Ignoring references when parsing Json Schema

### ISSUE THREAD

**Issue by gabriel9130** [tristanpenman/valijson#70]
Hello thanks for your work :) ,

Is there a way to ignore the references in the Json Schema when we are parsing it?

I juste needs the document once it's parsed. Most of the time the references are not valid and it's normal in my case: I use it to buid an OpenApi Schema object, and the definitions are juste else where.

So when I do:
parser.populateSchema(mySchemaAdapter, schema);

I get this exceptions --- > Expected reference token to identify an element in the current object actual token: " + referenceToken

To ignore the references, I tried the Contraint Builders, but I can't figure out how it works and there is no documentation for it.

Thank you!!

**Comment by tristanpenman** [comment]
Ignoring JSON references is something that falls outside of the original design constraints that I set for Valijson. Because it introduces a number of ambiguities (e.g. what is a valid document). That's the reason I'm reluctant to make changes to support unresolved references.

It's possible that you may be able to solve the problem using remote references, which is a way to provide support for JSON references that use URLs to point to different documents. Valijson is pretty flexible in this regard, and allows you to provide your own remote reference resolution function. An example is provided using curlpp, but you can probably hack this to do what you want.

I'm going to close this issue for now, but feel free to re-open it if you'd like to discuss it further.
