### ISSUE TITLE
JSON Schema draft v6 and v7 support

### ISSUE THREAD

**Issue by progsource** [tristanpenman/valijson#75]
Are there any plans to support drafts later than 4?

For example [draft 7](http://json-schema.org/draft-07/json-schema-release-notes.html)

**Comment by tristanpenman** [comment]
Apologies for the radio silence on this. I do have plans to support v6 and v7.

I'm not very familiar with the changes since v4, so it is hard to predict how long this will actually take, and whether it might involve deprecating/removing v4 support in the process.

I'll post updates to this issue as development progresses.

**Comment by tristanpenman** [comment]
Valijson now supports most of v7, with a few minor exceptions. The v6-and-v7-support branch has been merged into master now, so hopefully that supports the features you need.
